// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type PingResp struct {
	Message string `json:"message"`
	Time    string `json:"time"`
}

type RegisterReq struct {
	LongUrl string `json:"longUrl"`
}

type RegisterResp struct {
	Host     string `json:"host"`
	ShortKey string `json:"shortKey"`
	ShortUrl string `json:"shortUrl"`
}

type ShortRedirectionReq struct {
	ShortKey string `path:"shortKey"`
}

type ShortRedirectionResp struct {
	LongUrl string
}
