// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shortUrlsFieldNames          = builder.RawFieldNames(&ShortUrls{})
	shortUrlsRows                = strings.Join(shortUrlsFieldNames, ",")
	shortUrlsRowsExpectAutoSet   = strings.Join(stringx.Remove(shortUrlsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shortUrlsRowsWithPlaceHolder = strings.Join(stringx.Remove(shortUrlsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	shortUrlsModel interface {
		Insert(ctx context.Context, data *ShortUrls) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ShortUrls, error)
		FindOneByShortUrl(ctx context.Context, shortUrl string) (*ShortUrls, error)
		Update(ctx context.Context, data *ShortUrls) error
		Delete(ctx context.Context, id int64) error
	}

	defaultShortUrlsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ShortUrls struct {
		Id        int64     `db:"id"`
		ShortUrl  string    `db:"short_url"`
		LongUrl   string    `db:"long_url"`
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newShortUrlsModel(conn sqlx.SqlConn) *defaultShortUrlsModel {
	return &defaultShortUrlsModel{
		conn:  conn,
		table: "`short_urls`",
	}
}

func (m *defaultShortUrlsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultShortUrlsModel) FindOne(ctx context.Context, id int64) (*ShortUrls, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shortUrlsRows, m.table)
	var resp ShortUrls
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShortUrlsModel) FindOneByShortUrl(ctx context.Context, shortUrl string) (*ShortUrls, error) {
	var resp ShortUrls
	query := fmt.Sprintf("select %s from %s where `short_url` = ? limit 1", shortUrlsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, shortUrl)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShortUrlsModel) Insert(ctx context.Context, data *ShortUrls) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, shortUrlsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ShortUrl, data.LongUrl)
	return ret, err
}

func (m *defaultShortUrlsModel) Update(ctx context.Context, newData *ShortUrls) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, shortUrlsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ShortUrl, newData.LongUrl, newData.Id)
	return err
}

func (m *defaultShortUrlsModel) tableName() string {
	return m.table
}
